service: cloud-storage-wrapper-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${self:custom.bucketName}/*
  httpApi:
    cors: true
    authorizers:
      # Satisfies the local compiler while passing validation checks cleanly
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_EN5lKzo0m
        audience:
          - 5q4anpk5dom2md9q7udb4vd5lo
custom:
  bucketName: s9-master-bucket

functions:
  getUploadUrl:
    handler: handler.getUploadUrl
    events:
      - httpApi:
          path: /request-upload
          method: POST
          authorizer:
            name: cognitoAuthorizer
  # NEW: Add the retrieval route
  listFiles:
    handler: handler.listFiles
    events:
      - httpApi:
          path: /list-files
          method: GET
          authorizer:
            name: cognitoAuthorizer

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: cloud-wrapper-users-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: flutter-mobile-client
        UserPoolId: !Ref CognitoUserPool
        GenerateSecret: false

    HttpApiAuthorizerCognitoAuthorizer:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        Name: cloud-storage-cognito-authorizer
        ApiId: !Ref HttpApi
        AuthorizerType: JWT
        IdentitySource:
          - $request.header.Authorization
        AuthorizerResultTtlInSeconds: 0 # Disables the 20-minute authorization cache layer
        JwtConfiguration:
          Audience:
            - !Ref CognitoUserPoolClient
          Issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
    
    MasterStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
  # NEW: This forces AWS to spit out the exact IDs to your terminal screen
  Outputs:
    UserPoolId:
      Value: !Ref CognitoUserPool
      Description: "Use this value for _userPoolId in Flutter"
    UserPoolClientId:
      Value: !Ref CognitoUserPoolClient
      Description: "Use this value for _clientId in Flutter"